=== eclipse/mosaic/fed/mosaic-output/src/main/resources/output_config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://www.dcaiti.tu-berlin.de/research/simulation/download/get/specification/xs3p-1.1.3/xs3p.xsl"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <!-- COUNT: [MAS](#REF004): -->
    <xs:element name="configuration">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="output" />
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="output">
        <xs:complexType>
            <xs:sequence>
                <xs:choice>
                    <xs:sequence>
                        <xs:element minOccurs="0" ref="filename" />
                        <xs:element ref="directory" />
                        <xs:element ref="separator" />
                        <xs:element minOccurs="0" ref="decimalSeparator"/>
                    </xs:sequence>
                    <xs:sequence>
                        <xs:element ref="synchronized" />
                        <xs:element minOccurs="0" ref="host" />
                        <xs:element ref="port" />
                    </xs:sequence>
                    <xs:sequence>
                        <xs:element name="startTime" minOccurs="0" type="xs:string"/>
                        <xs:element name="upload">
                            <xs:complexType>
                                <xs:all>
                                    <xs:element ref="target" />
                                    <xs:element minOccurs="0" ref="scenarioId" />
                                    <xs:element minOccurs="0" ref="user" />
                                    <xs:element minOccurs="0" ref="password" />
                                </xs:all>
                                <xs:attribute name="enabled" type="xs:boolean" />
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:sequence>
                        <xs:element name="statistic">
                            <xs:complexType>
                                <xs:choice maxOccurs="unbounded">
                                    <xs:element minOccurs="1" ref="source" />
                                    <xs:element minOccurs="0" ref="group-by" />
                                    <xs:element minOccurs="0" ref="aggregation" />
                                    <xs:element minOccurs="0" ref="filter" />
                                </xs:choice>
                                <xs:attribute name="filename" type="xs:string" />
                                <xs:attribute name="output" type="xs:string" />
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:element ref="fences" />
                </xs:choice>
                <xs:element minOccurs="0" ref="append" />
                <xs:element minOccurs="0" ref="write" />
                <xs:element minOccurs="0" ref="clean" />
                <xs:element minOccurs="0" ref="test" />
                <xs:element minOccurs="0" ref="subscriptions" />
            </xs:sequence>
            <xs:attribute name="enabled" type="xs:boolean" />
            <xs:attribute name="id" use="required" type="xs:NCName" />
            <xs:attribute name="loader" use="required" />
            <xs:attribute name="update" type="xs:string" />
        </xs:complexType>
    </xs:element>
    <xs:element name="filename" type="xs:NCName">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                The filename for the specific log file.
            </xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="directory" type="xs:NMTOKEN">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                The directory to place the file in.
            </xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="separator" type="xs:string">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                The delimiter [.] can be escaped by a backslash [\.].
            </xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="decimalSeparator" type="xs:string">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                The separator for floating-point numbers.
            </xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="synchronized" type="xs:boolean" />
    <xs:element name="host" type="xs:NCName" />
    <xs:element name="port" type="xs:integer" />
    <xs:element name="append" type="xs:boolean">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Defines, whether the content will be appended to file.
                Default value: true;
            </xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="write" type="xs:string">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Its value can be file or log, which means using normal file writer or
                logback to handle the interaction.
                Default value: log;
            </xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="subscriptions">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="subscription" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="subscription">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="entries" />
            </xs:sequence>
            <xs:attribute name="enabled" type="xs:boolean" />
            <xs:attribute name="id" use="required" type="xs:NCName" />
        </xs:complexType>
    </xs:element>
    <xs:element name="entries">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="entry" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="entry" type="xs:anyURI" />
    <xs:element name="url" type="xs:string" />
    <xs:element name="user" type="xs:string" />
    <xs:element name="password" type="xs:string" />
    <xs:element name="clean" type="xs:boolean" />
    <xs:element name="test" type="xs:string" />
    <xs:element name="target" type="xs:string" />
    <xs:element name="scenarioId" type="xs:string" />
    <xs:element name="source" type="xs:string" />
    <xs:element name="group-by" type="xs:string" />
    <xs:element name="aggregation" type="xs:string" />
    <xs:element name="filter" >
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="filterType" type="xs:string" use="required" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="fences">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="rectangularFence">
                    <xs:complexType>
                        <xs:attribute name="north" type="xs:double" use="required" />
                        <xs:attribute name="east" type="xs:double" use="required" />
                        <xs:attribute name="west" type="xs:double" use="required" />
                        <xs:attribute name="south" type="xs:double" use="required" />
                        <xs:attribute name="start" type="xs:int" />
                        <xs:attribute name="end" type="xs:int" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="circularFence">
                    <xs:complexType>
                        <xs:attribute name="centerLat" type="xs:double" use="required" />
                        <xs:attribute name="centerLon" type="xs:double" use="required" />
                        <xs:attribute name="radius" type="xs:int" use="required" />
                        <xs:attribute name="start" type="xs:int" />
                        <xs:attribute name="end" type="xs:int" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="timeFence">
                    <xs:complexType>
                        <xs:attribute name="start" type="xs:int" use="required" />
                        <xs:attribute name="end" type="xs:int" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== eclipse/mosaic/bundle/src/assembly/resources/scenarios/Barnim/output/output_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- file version: 2013-11-26 -->
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/eclipse/mosaic/main/fed/mosaic-output/src/main/resources/output_config.xsd">

    <output id="fileoutput" enabled="true" update="5" loader="org.eclipse.mosaic.fed.output.generator.file.FileOutputLoader">
        <filename>output.csv</filename>
        <directory>.</directory>
        <separator>;</separator>
        <subscriptions>
            <subscription id="VehicleUpdates">
                <entries>
                    <entry>"VEHICLE_UPDATES"</entry>
                    <entry>Time</entry>
                    <entry>Updated:Name</entry>
                    <entry>Updated:Speed</entry>
                    <entry>Updated:Heading</entry>
                    <entry>Updated:Position.Latitude</entry>
                    <entry>Updated:Position.Longitude</entry>
                    <entry>Updated:Position.Altitude</entry>
                    <entry>Updated:DistanceDriven</entry>
                    <entry>Updated:LongitudinalAcceleration</entry>
                    <entry>Updated:Slope</entry>
                    <entry>Updated:Stopped</entry>
                    <entry>Updated:RouteId</entry>
                    <entry>Updated:RoadPosition.Connection.Id</entry>
                    <entry>Updated:RoadPosition.LaneIndex</entry>
                    <entry>Updated:VehicleEmissions.CurrentEmissions.Co2</entry>
                    <entry>Updated:VehicleEmissions.CurrentEmissions.Co</entry>
                    <entry>Updated:VehicleEmissions.CurrentEmissions.Hc</entry>
                    <entry>Updated:VehicleEmissions.CurrentEmissions.Pmx</entry>
                    <entry>Updated:VehicleEmissions.CurrentEmissions.Nox</entry>
                    <entry>Updated:VehicleConsumptions.CurrentConsumptions.Fuel</entry>
                    <entry>Updated:VehicleEmissions.AllEmissions.Co2</entry>
                    <entry>Updated:VehicleEmissions.AllEmissions.Co</entry>
                    <entry>Updated:VehicleEmissions.AllEmissions.Hc</entry>
                    <entry>Updated:VehicleEmissions.AllEmissions.Pmx</entry>
                    <entry>Updated:VehicleEmissions.AllEmissions.Nox</entry>
                    <entry>Updated:VehicleConsumptions.AllConsumptions.Fuel</entry>
                    <entry>Updated:VehicleSignals.BlinkerRight</entry>
                    <entry>Updated:VehicleSignals.BlinkerLeft</entry>
                    <entry>Updated:VehicleSignals.BrakeLight</entry>
                </entries>
            </subscription>
            <subscription id="V2xMessageReception">
                <entries>
                    <entry>"V2X_MESSAGE_RECEPTION"</entry>
                    <entry>Time</entry>
                    <entry>Type</entry>
                    <entry>MessageId</entry>
                    <entry>ReceiverName</entry>
                    <entry>ReceiverInformation.ReceiveSignalStrength</entry>
                </entries>
            </subscription>
            <subscription id="V2xMessageTransmission">
                <entries>
                    <entry>"V2X_MESSAGE_TRANSMISSION"</entry>
                    <entry>Time</entry>
                    <entry>Type</entry>
                    <entry>MessageId</entry>
                    <entry>SourceName</entry>
                    <entry>SourcePosition.Latitude</entry>
                    <entry>SourcePosition.Longitude</entry>
                    <entry>SourcePosition.Altitude</entry>
                    <entry>Message.Routing.Destination.Type</entry>
                    <entry>Message.Routing.Destination.Address.IPv4Address</entry>
                    <entry>Message.Routing.Destination.AdhocChannelId</entry>
                </entries>
            </subscription>
            <subscription id="VehicleRegistration" enabled="true">
                <entries>
                    <entry>"VEHICLE_REGISTRATION"</entry>
                    <entry>Time</entry>
                    <entry>Mapping.Name</entry>
                    <entry>Mapping.Applications</entry>
                    <entry>Mapping.VehicleType.VehicleClass</entry>
                    <entry>Mapping.VehicleType.Color</entry>
                    <entry>Mapping.Group</entry>
                    <entry>Mapping.VehicleType.Length</entry>
                    <entry>Mapping.VehicleType.MinGap</entry>
                    <entry>Mapping.VehicleType.MaxSpeed</entry>
                    <entry>Mapping.VehicleType.Accel</entry>
                    <entry>Mapping.VehicleType.Decel</entry>
                    <entry>Mapping.VehicleType.Sigma</entry>
                    <entry>Mapping.VehicleType.Tau</entry>
                    <entry>Mapping.VehicleType.SpeedFactor</entry>
                    <entry>Departure.RouteId</entry>
                    <entry>Departure.DepartureLane</entry>
                    <entry>Departure.DeparturePos</entry>
                </entries>
            </subscription>
            <subscription id="TrafficLightRegistration">
                <entries>
                    <entry>"TRAFFICLIGHT_REGISTRATION"</entry>
                    <entry>Time</entry>
                    <entry>Mapping.Name</entry>
                    <entry>Mapping.Applications</entry>
                    <entry>TrafficLightGroup.FirstPosition.Latitude</entry>
                    <entry>TrafficLightGroup.FirstPosition.Longitude</entry>
                </entries>
            </subscription>
            <subscription id="TrafficSignRegistration">
                <entries>
                    <entry>"TRAFFICSIGN_REGISTRATION"</entry>
                    <entry>Time</entry>
                    <entry>TrafficSign.Id</entry>
                    <entry>TrafficSign.GeoPosition.Latitude</entry>
                    <entry>TrafficSign.GeoPosition.Longitude</entry>
                    <entry>TrafficSign.GeoPosition.Altitude</entry>
                    <entry>TrafficSign.Angle</entry>
                    <entry>TrafficSign.ConnectionId</entry>
                    <entry>TrafficSign.Lane</entry>
                    <entry>TrafficSign.TypeId</entry>
                    <entry>TrafficSign.SignContents</entry>
                </entries>
            </subscription>
            <subscription id="VehicleSpeedChange">
                <entries>
                    <entry>"CHANGE_SPEED"</entry>
                    <entry>Time</entry>
                    <entry>VehicleId</entry>
                    <entry>Type</entry>
                    <entry>Speed</entry>
                    <entry>Interval</entry>
                    <entry>Acceleration</entry>
                </entries>
            </subscription>
            <subscription id="ServerRegistration">
                <entries>
                    <entry>"SERVER_REGISTRATION"</entry>
                    <entry>Time</entry>
                    <entry>Mapping.Name</entry>
                    <entry>Mapping.Group</entry>
                    <entry>Mapping.Applications</entry>
                </entries>
            </subscription>
            <subscription id="AdHocCommunicationConfiguration">
                <entries>
                    <entry>"ADHOC_CONFIGURATION"</entry>
                    <entry>Time</entry>
                    <entry>Configuration.NodeId</entry>
                    <entry>Configuration.RadioMode</entry>
                    <entry>Configuration.Conf0.NewIP</entry>
                    <entry>Configuration.Conf0.NewPower</entry>
                    <entry>Configuration.Conf0.Channel0</entry>
                    <entry>Configuration.Conf0.Channel1</entry>
                    <entry>Configuration.Conf1.NewIP</entry>
                    <entry>Configuration.Conf1.NewPower</entry>
                    <entry>Configuration.Conf1.Channel0</entry>
                    <entry>Configuration.Conf1.Channel1</entry>
                </entries>
            </subscription>
            <subscription id="CellularCommunicationConfiguration">
                <entries>
                    <entry>"CELL_CONFIGURATION"</entry>
                    <entry>Time</entry>
                    <entry>Configuration.NodeId</entry>
                    <entry>Configuration.Enabled</entry>
                    <entry>Configuration.MaxDownlinkBitrate</entry>
                    <entry>Configuration.MaxUplinkBitrate</entry>
                </entries>
            </subscription>
            <subscription id="TrafficDetectorUpdates">
                <entries>
                    <entry>"DETECTOR_UPDATES"</entry>
                    <entry>Time</entry>
                    <entry>UpdatedInductionLoops:VehicleCount</entry>
                    <entry>UpdatedInductionLoops:MeanSpeed</entry>
                    <entry>UpdatedInductionLoops:TrafficFlow</entry>
                    <entry>UpdatedLaneAreaDetectors:Length</entry>
                    <entry>UpdatedLaneAreaDetectors:VehicleCount</entry>
                    <entry>UpdatedLaneAreaDetectors:MeanSpeed</entry>
                </entries>
            </subscription>
            <subscription id="LanePropertyChange">
                <entries>
                    <entry>"LANE_PROPERTY_CHANGE"</entry>
                    <entry>Time</entry>
                    <entry>EdgeId</entry>
                    <entry>LaneIndex</entry>
                    <entry>AllowedVehicleClasses</entry>
                    <entry>DisallowedVehicleClasses</entry>
                    <entry>MaxSpeed</entry>
                </entries>
            </subscription>
        </subscriptions>
    </output>

    <output id="websocket" enabled="true" loader="org.eclipse.mosaic.fed.output.generator.websocket.WebsocketVisualizerLoader">
        <synchronized>true</synchronized>
        <port>46587</port>
        <subscriptions>
            <subscription id="VehicleUpdates" enabled="true"/>
